# Services to run the Rapid Evaluation Framework (REF) metric workers
# These can be started by running `docker-compose up` in the root directory of the codebase.

name: climate-ref
services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  flower:
    image: mher/flower
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    ports:
      - "5555:5555"
    depends_on:
      - redis
  # Worker to track the results of async tasks
  ref:
    image: ref
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - REF_EXECUTOR=climate_ref_celery.executor.CeleryExecutor
      - REF_METRIC_PROVIDERS=climate_ref_example
    build:
      context: .
      dockerfile: packages/ref/Dockerfile
      platforms:
        - linux/amd64
    command: ref celery start-worker
    volumes:
      - ./tests/test-data/sample-data:/ref/data
      - ref:/ref
  # Worker to run the example metrics
  metrics-example:
    image: ref
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    command: ref celery start-worker --package climate_ref_example
    volumes:
      - ./tests/test-data/sample-data:/ref/data
      - ref:/ref
volumes:
  ref:
