# Services to run the Rapid Evaluation Framework (REF) diagnostic workers
# These can be started by running `docker-compose up` in the root directory of the codebase.

name: climate-ref
services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  flower:
    image: mher/flower
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    ports:
      - "5555:5555"
    depends_on:
      - redis
  # Base worker to track the executions of async tasks
  climate-ref-worker:
    image: ghcr.io/climate-ref/climate-ref:latest
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - REF_EXECUTOR=climate_ref_celery.executor.CeleryExecutor
    build:
      context: .
      dockerfile: packages/climate-ref/Dockerfile
      platforms:
        - linux/amd64
    command: ref celery start-worker
    volumes:
      - ./tests/test-data/sample-data:/ref/data
      - ref:/ref
  # ESMValTool metrics worker
  metrics-esmvaltool:
    image: ghcr.io/climate-ref/climate-ref-esmvaltool:latest
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    build:
      context: .
      dockerfile: packages/climate-ref-esmvaltool/Dockerfile
      platforms:
        - linux/amd64
    volumes:
      - ./tests/test-data/sample-data:/ref/data
      - ref:/ref
  # ILAMB metrics worker
  metrics-ilamb:
    image: ghcr.io/climate-ref/climate-ref-ilamb:latest
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    build:
      context: .
      dockerfile: packages/climate-ref-ilamb/Dockerfile
      platforms:
        - linux/amd64
    volumes:
      - ./tests/test-data/sample-data:/ref/data
      - ref:/ref
  # PMP metrics worker
  metrics-pmp:
    image: ghcr.io/climate-ref/climate-ref-pmp:latest
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    build:
      context: .
      dockerfile: packages/climate-ref-pmp/Dockerfile
      platforms:
        - linux/amd64
    volumes:
      - ./tests/test-data/sample-data:/ref/data
      - ref:/ref

volumes:
  ref:
