target-version = "py310"
line-length = 110

[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "D",
    "PL",
    "NPY",
    "RUF",
    "UP",
    "S",
    "A",
]
unfixable = [
    "PD002",
]
ignore = [
    "D100",
    "D105", # Missing docstring in magic method
    "D200",
    "D400",
    "UP007",
    "S101",  # Use of `assert` detected
]

[lint.per-file-ignores]
"test*.py" = [
    "D",  # Documentation not needed in tests
    "PLR2004", # Magic value used in comparison
    "PLR0913", # Too many arguments in function definition
    "PLR6301", # Class functions
    "PLC2701", # Private named import
]
"conftest.py" = [
    "D",  # Documentation not needed in tests
    "PLR2004" # Magic value used in comparison
]
"docs/*" = [
    "D",
    "E402",  # Module level import not at top of file
    "PLR2004",  # Magic value used in comparison.
]
"*/migrations/versions/*" = [
    "D103",  # Missing docstring in public function
]
"stubs/*" = [
    "PLR0913",  # Too many arguments in function definition
]

[lint.isort]
known-first-party = ["climate_ref", "climate_ref_core"]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
