{{- range $provider, $spec := (omit .Values.providers "defaults") -}}
{{- $spec := merge (deepCopy $.Values.defaults) $spec -}}
{{- if and $spec.serviceAccount $spec.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ref.fullname" $ }}-{{ $provider }}
  labels:
    app.kubernetes.io/component: {{ $provider }}
    {{- include "ref.labels" $ | nindent 4 }}
  {{- with $spec.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $spec.serviceAccount.automount }}
{{- end }}
---
{{- end }}
