[project]
name = "climate-ref-example"
version = "0.6.4"
description = "Example diagnostic provider for the Rapid Evaluation Framework"
readme = "README.md"
authors = [
    { name = "Jared Lewis", email = "jared.lewis@climate-resource.com" }
]
license = "Apache-2.0"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "climate-ref-core",
    "xarray >= 2022",
    "netcdf4>=1.5.0",
    "dask>=2024.10.0",
]
[project.entry-points."climate-ref.providers"]
example = "climate_ref_example:provider"

[dependency-groups]
dev = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
