channels:
  - conda-forge
  - nodefaults

dependencies:
  - cartopy
  - cf-units
  - dask
  - esmvaltool-base
  - iris
  - mapgenerator
  - matplotlib-base
  - numpy
  - pandas
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - yaml
