"""Use 'version' as version facet for obs4MIPs

Revision ID: aa4522d61259
Revises: ba5e
Create Date: 2025-08-26 17:10:48.765237

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa4522d61259"
down_revision: Union[str, None] = "ba5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("obs4mips_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("obs4mips_dataset", schema=None) as batch_op:
        batch_op.drop_column("version")

    # ### end Alembic commands ###
