"""add calendar and drop parent_time_units

Revision ID: 26c321a1c85a
Revises: 2f6e36738e06
Create Date: 2025-09-24 17:33:54.108388

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26c321a1c85a"
down_revision: Union[str, None] = "2f6e36738e06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cmip6_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("calendar", sa.String(), nullable=True))
        batch_op.drop_column("parent_time_units")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cmip6_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_time_units", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("calendar")

    # ### end Alembic commands ###
