"""add CMIP7 tables

Revision ID: ed30a1d12209
Revises: 20cd136a5b04
Create Date: 2026-01-13 20:38:09.188101

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed30a1d12209"
down_revision: Union[str, None] = "20cd136a5b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cmip7_dataset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.String(), nullable=False),
        sa.Column("institution_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=False),
        sa.Column("variant_label", sa.String(), nullable=False),
        sa.Column("variable_id", sa.String(), nullable=False),
        sa.Column("grid_label", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("mip_era", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("frequency", sa.String(), nullable=False),
        sa.Column("branding_suffix", sa.String(), nullable=False),
        sa.Column("branded_variable", sa.String(), nullable=False),
        sa.Column("temporal_label", sa.String(), nullable=True),
        sa.Column("vertical_label", sa.String(), nullable=True),
        sa.Column("horizontal_label", sa.String(), nullable=True),
        sa.Column("area_label", sa.String(), nullable=True),
        sa.Column("drs_specs", sa.String(), nullable=False),
        sa.Column("data_specs_version", sa.String(), nullable=False),
        sa.Column("product", sa.String(), nullable=False),
        sa.Column("license_id", sa.String(), nullable=False),
        sa.Column("realization_index", sa.String(), nullable=True),
        sa.Column("initialization_index", sa.String(), nullable=True),
        sa.Column("physics_index", sa.String(), nullable=True),
        sa.Column("forcing_index", sa.String(), nullable=True),
        sa.Column("realm", sa.String(), nullable=True),
        sa.Column("nominal_resolution", sa.String(), nullable=True),
        sa.Column("tracking_id", sa.String(), nullable=True),
        sa.Column("standard_name", sa.String(), nullable=True),
        sa.Column("long_name", sa.String(), nullable=True),
        sa.Column("units", sa.String(), nullable=True),
        sa.Column("branch_time_in_child", sa.Float(), nullable=True),
        sa.Column("branch_time_in_parent", sa.Float(), nullable=True),
        sa.Column("parent_activity_id", sa.String(), nullable=True),
        sa.Column("parent_experiment_id", sa.String(), nullable=True),
        sa.Column("parent_mip_era", sa.String(), nullable=True),
        sa.Column("parent_source_id", sa.String(), nullable=True),
        sa.Column("parent_time_units", sa.String(), nullable=True),
        sa.Column("parent_variant_label", sa.String(), nullable=True),
        sa.Column("external_variables", sa.String(), nullable=True),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["dataset.id"], name=op.f("fk_cmip7_dataset_id_dataset")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cmip7_dataset")),
    )
    with op.batch_alter_table("cmip7_dataset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cmip7_dataset_experiment_id"), ["experiment_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cmip7_dataset_instance_id"), ["instance_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cmip7_dataset_source_id"), ["source_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cmip7_dataset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cmip7_dataset_source_id"))
        batch_op.drop_index(batch_op.f("ix_cmip7_dataset_instance_id"))
        batch_op.drop_index(batch_op.f("ix_cmip7_dataset_experiment_id"))

    op.drop_table("cmip7_dataset")
    # ### end Alembic commands ###
