"""add license_id and external_variables to cmip7

Revision ID: 0baa5a386d99
Revises: c47703d514ba
Create Date: 2026-02-05 23:57:28.323566

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0baa5a386d99"
down_revision: Union[str, None] = "c47703d514ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cmip7_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("license_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("external_variables", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cmip7_dataset", schema=None) as batch_op:
        batch_op.drop_column("external_variables")
        batch_op.drop_column("license_id")

    # ### end Alembic commands ###
