"""add time_units and calendar to cmip6_dataset and cmip7_dataset

Also changes dataset_file.start_time and end_time from DateTime to String
to support cftime dates (e.g. 360-day calendar dates like Feb 30).

Revision ID: a3b4c5d6e7f8
Revises: 0baa5a386d99
Create Date: 2026-02-26 00:00:00.000000

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3b4c5d6e7f8"
down_revision: Union[str, None] = "0baa5a386d99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cmip6_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("time_units", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("calendar", sa.String(), nullable=True))

    with op.batch_alter_table("cmip7_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("time_units", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("calendar", sa.String(), nullable=True))

    # Change dataset_file.start_time and end_time from DateTime to String
    # to support cftime dates that can't be represented as datetime.datetime
    with op.batch_alter_table("dataset_file", schema=None) as batch_op:
        batch_op.alter_column(
            "start_time",
            existing_type=sa.DateTime(),
            type_=sa.String(),
            nullable=True,
        )
        batch_op.alter_column(
            "end_time",
            existing_type=sa.DateTime(),
            type_=sa.String(),
            nullable=True,
        )

    # Trigger re-finalisation of all datasets to populate the new columns
    # and re-serialise start_time/end_time as strings
    op.execute("UPDATE dataset SET finalised=FALSE WHERE dataset_type='CMIP6'")
    op.execute("UPDATE dataset SET finalised=FALSE WHERE dataset_type='CMIP7'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Restore dataset_file.start_time and end_time to DateTime
    # PostgreSQL requires an explicit USING cast for String -> DateTime
    with op.batch_alter_table("dataset_file", schema=None) as batch_op:
        batch_op.alter_column(
            "start_time",
            existing_type=sa.String(),
            type_=sa.DateTime(),
            nullable=True,
            postgresql_using="start_time::timestamp without time zone",
        )
        batch_op.alter_column(
            "end_time",
            existing_type=sa.String(),
            type_=sa.DateTime(),
            nullable=True,
            postgresql_using="end_time::timestamp without time zone",
        )

    with op.batch_alter_table("cmip7_dataset", schema=None) as batch_op:
        batch_op.drop_column("calendar")
        batch_op.drop_column("time_units")

    with op.batch_alter_table("cmip6_dataset", schema=None) as batch_op:
        batch_op.drop_column("calendar")
        batch_op.drop_column("time_units")

    # ### end Alembic commands ###
