{{- if .Values.ref.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ref.fullname" . }}-ref
  labels:
    app.kubernetes.io/component: ref
    {{- include "ref.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ref.fullname" . }}-ref
  minReplicas: {{ .Values.ref.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ref.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.ref.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ref.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.ref.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ref.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
