{{- if .Values.ref.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ref.fullname" . }}-ref
  labels:
    app.kubernetes.io/component: ref
    {{- include "ref.labels" . | nindent 4 }}
  {{- with .Values.ref.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ref.serviceAccount.automount }}
{{- end }}
