{{- range $pkg, $spec := .Values.packages }}
{{- if and $spec.serviceAccount $spec.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ref.fullname" $ }}-{{ $pkg }}
  labels:
    app.kubernetes.io/component: {{ $pkg }}
    {{- include "ref.labels" $ | nindent 4 }}
  {{- with $spec.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $spec.serviceAccount.automount }}
{{- end }}
{{- end }}
