"""add doi and tracking_id to metadata tracking

Revision ID: c058c4ccf383
Revises: c5de99c14533
Create Date: 2025-04-04 16:01:26.205824

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c058c4ccf383"
down_revision: Union[str, None] = "c5de99c14533"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric_execution_result", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_metric_execution_result_metric_execution_group_id_metric_execution_group",  # <-- Name added
            "metric_execution_group",
            ["metric_execution_group_id"],
            ["id"],
        )

    with op.batch_alter_table("obs4mips_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("doi", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("references", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("tracking_id", sa.String(), nullable=True))
        batch_op.alter_column("variant_label", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("obs4mips_dataset", schema=None) as batch_op:
        batch_op.alter_column("variant_label", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("tracking_id")
        batch_op.drop_column("references")
        batch_op.drop_column("doi")

    with op.batch_alter_table("metric_execution_result", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_metric_execution_result_metric_execution_group_id_metric_execution_group",  # <-- Name added
            type_="foreignkey",
        )

    # ### end Alembic commands ###
