"""add uncertainty information attributes

Revision ID: dc2393b21436
Revises: c058c4ccf383
Create Date: 2025-04-04 16:24:14.505451

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc2393b21436"
down_revision: Union[str, None] = "c058c4ccf383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("obs4mips_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("has_auxdata", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("aux_variable_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("obs4mips_dataset", schema=None) as batch_op:
        batch_op.drop_column("aux_variable_id")
        batch_op.drop_column("has_auxdata")

    # ### end Alembic commands ###
