apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ref.fullname" . }}-flower
  labels:
    app.kubernetes.io/component: flower
    {{- include "ref.labels" . | nindent 4 }}
stringData:
  {{- tpl (toYaml .Values.flower.env) . | nindent 2}}
