{{- if .Values.flower.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ref.fullname" . }}-flower
  labels:
    app.kubernetes.io/component: flower
    {{- include "ref.labels" . | nindent 4 }}
  {{- with .Values.flower.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.flower.serviceAccount.automount }}
{{- end }}
