name: Build Containers

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  climate-ref:
    name: climate-ref
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-container
        with:
          container-name: climate-ref
          dockerfile: packages/climate-ref/Dockerfile
  climate-ref-esmvaltool:
    name: climate-ref-esmvaltool
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-container
        with:
          container-name: climate-ref-esmvaltool
          dockerfile: packages/climate-ref-esmvaltool/Dockerfile
  climate-ref-pmp:
    name: climate-ref-pmp
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-container
        with:
          container-name: climate-ref-pmp
          dockerfile: packages/climate-ref-pmp/Dockerfile
  climate-ref-ilamb:
    name: climate-ref-ilamb
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-container
        with:
          container-name: climate-ref-ilamb
          dockerfile: packages/climate-ref-ilamb/Dockerfile
