name: Helm chart

on:
  pull_request:
  push:
    tags:
    - 'v*'

permissions: {}

jobs:
  test:
    name: Test Helm Chart
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
    - name: Install Helm Chart
      run: |
        PR_NUMBER=$(echo ${GITHUB_REF} | awk -F'/' '{print $3}')

        helm dependency update

        helm install test ./helm \
          --set ref.image.tag=pr-${PR_NUMBER} \
          --wait

        kubectl get pods

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: ref
        repository: climate-ref
        tag: ${{ github.ref_name }}
        path: helm
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'
